name: Deploy the helm chart to Okteto

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        description: Version to bump to
      service-name:
        type: string
        required: true
        description: Helm name
      helm-chart:
        type: string
        required: true
        description: Helm chart to deploy
      chart-location:
        type: string
        required: true
        description: "Location of the helm chart museum"
      namespace:
        type: string
        required: true
        description: "K8s Namespace"
    secrets:
      kube-config:
        description: 'Kube config file to talk to the the k8s cluster'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: |
            helm repo add vivinsure ${{ inputs.chart-location }}
            helm repo update
            echo "helm upgrade ${{ inputs.service-name }} ${{ inputs.helm-chart }} --install --namespace ${{ inputs.namespace }} --version ${{ inputs.version }}"
            helm upgrade ${{ inputs.service-name }} ${{ inputs.helm-chart }} --install --namespace ${{ inputs.namespace }} --version ${{ inputs.version }}
          kubeconfig: '${{ secrets.kube-config }}'


